
{REDUND_ERROR} FUNCTION_BLOCK DRIVE (*TODO: Add your comment here*) (*$GROUP=User,$CAT=User,$GROUPICON=User.png,$CATICON=User.png*)
	VAR_INPUT
		ENABLE : {REDUND_UNREPLICABLE} BOOL;
		STATE : {REDUND_UNREPLICABLE} UINT;
	END_VAR
	VAR_OUTPUT
		REAL_SPEED : {REDUND_UNREPLICABLE} INT;
		COMMAND : {REDUND_UNREPLICABLE} UINT;
	END_VAR
END_FUNCTION_BLOCK
